---
- name: make tmp dir for all files
  file:
    path: /tmp/deploy/
    state: directory
    mode: '0755'

- name: copy oozie workflow and coordinator xmls to target dir
  copy: 
    src: ../template/{{ item }}
    dest: /tmp/deploy/{{ item }}
  with_items:
    - workflow.xml
    - coordinator.xml

- name: templating oozie job config to put throw API
  template: 
    src: ../template/config.xml.j2
    dest: /tmp/deploy/config.xml

- name: copy keytab to tmp dir
  copy:
    src: ../template/{{ hadoop_user }}.keytab
    dest: /tmp/deploy/{{ hadoop_user }}.keytab

- name: aothentificate in kerberos with keytab
  shell: kinit -kt {{ hadoop_user }}.keytab {{ hadoop_user }}@{{ krb_suffix }}
  args:
    chdir: /tmp/deploy/
    executable: /bin/bash

- name: make klist for print our ticket to make future error handling easy
  shell: klist
  args:
    executable: /bin/bash
  register: klist

- debug: klist.stdout_lines


