---
- name: make tmp dir for all files
  file:
    path: /tmp/deploy/
    state: directory
    mode: '0755'

- name: make var for start_date
  shell: date --date='5 minutes ago' --utc +%FT%H:%MZ
  args:
    executable: /bin/bash
  register: start_date

- name: make var for end date
  shell: date --date='90 years' --utc +%FT%H:%MZ
  args:
    executable: /bin/bash
  register: end_date

- name: make param for dirname in hdfs
  shell: echo "{{ ansible_date_time.epoch }}"
  register: hdfs_dirname

#- name: unzip the archive with files to future workdir
#  unarchive:
#    src: release.zip
#    dest: /tmp/deploy

- name: copy oozie workflow and coordinator xmls to target dir
  copy: 
    src: templates/{{ item }}
    dest: /tmp/deploy/{{ item }}
  loop:
    - workflow.xml
    - coordinator.xml
    - test.sh

- name: templating oozie job config to put throw API
  template: 
    src: templates/config.xml.j2
    dest: /tmp/deploy/config.xml

- name: copy keytab to tmp dir
  copy:
    src: templates/{{ hadoop_user }}.keytab
    dest: /tmp/deploy/{{ hadoop_user }}.keytab

- name: auth in kerberos with keytab
  shell: kinit -kt {{ hadoop_user }}.keytab {{ krb_princ }}@{{ krb_suffix }}
  args:
    chdir: /tmp/deploy/
    executable: /bin/bash


