---
- name: say hello
  debug: msg="Start putting files to HDFS"


- name: create dir in hdfs throw api
  shell: curl --negotiate -X PUT -u {{ ':' }} 'http://{{ httpfs_url }}/webhdfs/v1/user/{{ hadoop_user }}/{{ hdfs_dirname.stdout }}?op=MKDIRS&&user.name={{ hadoop_user }}&createParent=true'
  args:
    chdir: /tmp/deploy/
    executable: /bin/bash


- name: put files to hdfs throw api
  shell: curl --negotiate -X PUT -L -u {{ ':' }} 'http://{{ httpfs_url }}/webhdfs/v1/user/{{ hadoop_user }}/{{ hdfs_dirname.stdout }}/{{ item }}?op=CREATE&&user.name={{ hadoop_user }}' --header 'Content-Type{{ ":" }} application/octet-stream' -T ./{{ item }}
  args:
    chdir: /tmp/deploy/
    executable: /bin/bash
  loop:
    - "workflow.xml"
    - "coordinator.xml"
    - "run.sh"

- name: say end
  debug: msg="Put to hdfs is over. Ready for next step"
