---
- name: make sure the directory exists
  stat:
    path: /tmp/deploy
  register: deploy_dir

- name: put files to hdfs throw api
  shell: curl --negotiate -X PUT -L -u : "http://{{ httpfs_url }}/webhdfs/v1/user/{{ hadoop_user }}/{{ item }}?op=CREATE&&user.name={{ hadoop_user }}" --header 'Content-Type: application/octet-stream' -T ./{{ item }}
  args:
    chdir: /tmp/deploy/
    executable: /bin/bash
  with_items:
    - wokrflow.xml
    - coordinator.xml
    - carbondata.jar
    - test.sh
  when: deploy_dir.stat.exists


